apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: payment
      volumes:
      - name: config
        configMap:
          name: payment-config
      - name: spiffe-workload-api
        csi:
          driver: csi.spiffe.io
          readOnly: true
      containers:
      - name: payment
        image: payment:local
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8081"
        - name: FRAUD_URL
          value: "http://127.0.0.1:15001"
        ports:
        - containerPort: 8081
      - name: envoy
        image: envoyproxy/envoy:v1.28.2
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - /etc/envoy/envoy.yaml
        - --log-level
        - info
        ports:
        - containerPort: 8080
        - containerPort: 15001
        - containerPort: 9901
        volumeMounts:
        - name: config
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy.yaml
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
