apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment
  namespace: lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud
  namespace: lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: lab
