apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-fraud
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-fraud
  template:
    metadata:
      labels:
        app: opa-fraud
    spec:
      serviceAccountName: opa-fraud
      volumes:
      - name: config
        configMap:
          name: opa-fraud-config
      - name: policy
        configMap:
          name: opa-fraud-policy
      - name: spiffe-workload-api
        csi:
          driver: csi.spiffe.io
          readOnly: true
      containers:
      - name: opa
        image: openpolicyagent/opa:0.63.0-envoy
        imagePullPolicy: IfNotPresent
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        args:
        - run
        - --server
        - --config-file=/config/opa-config.yaml
        - /policies
        volumeMounts:
        - name: config
          mountPath: /config/opa-config.yaml
          subPath: opa-config.yaml
        - name: policy
          mountPath: /policies/policy.rego
          subPath: policy.rego
      - name: envoy
        image: envoyproxy/envoy:v1.28.2
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - /etc/envoy/envoy.yaml
        - --log-level
        - info
        ports:
        - containerPort: 8080
        - containerPort: 15002
        - containerPort: 9901
        volumeMounts:
        - name: config
          mountPath: /etc/envoy/envoy.yaml
          subPath: envoy.yaml
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
