apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-payment-config
  namespace: lab
data:
  envoy.yaml: |
    node:
      id: opa-payment
      cluster: opa-payment
    static_resources:
      listeners:
      - name: inbound
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              require_client_certificate: true
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: spiffe://example.org/ns/lab/sa/opa-payment
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                      - envoy_grpc:
                          cluster_name: spire_agent
                      transport_api_version: V3
                combined_validation_context:
                  default_validation_context:
                    match_subject_alt_names:
                    - exact: spiffe://example.org/ns/lab/sa/payment
                  validation_context_sds_secret_config:
                    name: spiffe://example.org
                    sds_config:
                      api_config_source:
                        api_type: GRPC
                        grpc_services:
                        - envoy_grpc:
                            cluster_name: spire_agent
                        transport_api_version: V3
          filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: inbound_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: opa
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: opa_grpc
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      - name: egress
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 15002
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: egress_http
              route_config:
                name: egress_route
                virtual_hosts:
                - name: entitlements
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: entitlements
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: opa_grpc
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        load_assignment:
          cluster_name: opa_grpc
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9191
      - name: entitlements
        connect_timeout: 0.5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: entitlements
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: entitlements.lab.svc.cluster.local
                    port_value: 8080
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: entitlements.lab
            common_tls_context:
              tls_certificate_sds_secret_configs:
              - name: spiffe://example.org/ns/lab/sa/opa-payment
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                    - envoy_grpc:
                        cluster_name: spire_agent
                    transport_api_version: V3
              combined_validation_context:
                default_validation_context:
                  match_subject_alt_names:
                  - exact: spiffe://example.org/ns/lab/sa/entitlements
                validation_context_sds_secret_config:
                  name: spiffe://example.org
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                      - envoy_grpc:
                          cluster_name: spire_agent
                      transport_api_version: V3
      - name: spire_agent
        connect_timeout: 0.25s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: spire_agent
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  pipe:
                    path: /spiffe-workload-api/spire-agent.sock
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
